import { describe, it, expect } from 'vitest'
import { parseDnsmasq } from '../dnsmasq'

describe('parseDnsmasq', () => {
  // ── Temel format testleri ─────────────────────────────────────
  it('address=/domain/ip formatını işler', () => {
    expect(parseDnsmasq('address=/ads.example.com/0.0.0.0')).toContain('ads.example.com')
  })

  it('address=/domain/ (IP yok) formatını işler', () => {
    expect(parseDnsmasq('address=/tracker.io/')).toContain('tracker.io')
  })

  it('server=/domain/# formatını işler', () => {
    expect(parseDnsmasq('server=/malware.bad.com/#')).toContain('malware.bad.com')
  })

  it('address=/domain/127.0.0.1 formatını işler', () => {
    expect(parseDnsmasq('address=/cdn.ads.net/127.0.0.1')).toContain('cdn.ads.net')
  })

  // ── local= desteği (Hagezi ve benzeri listeler) ───────────────
  it('local=/domain/ip Hagezi formatını işler', () => {
    expect(parseDnsmasq('local=/ads.hagezi.com/0.0.0.0')).toContain('ads.hagezi.com')
  })

  it('local=/domain/ (IP yok) formatını işler', () => {
    expect(parseDnsmasq('local=/tracker.evil.com/')).toContain('tracker.evil.com')
  })

  it('local=/domain/127.0.0.1 formatını işler', () => {
    expect(parseDnsmasq('local=/cdn.malware.net/127.0.0.1')).toContain('cdn.malware.net')
  })

  it('local=/internal/ tek etiketli (TLD yok) geçersiz domain atlar', () => {
    // "internal" tek etiketli — regex eşleşmez, atlanır
    const input = 'local=/internal/'
    expect(parseDnsmasq(input)).toHaveLength(0)
  })

  // ── Temel davranış testleri ───────────────────────────────────
  it('yorum satırlarını (#) atlar', () => {
    const input = '# dnsmasq config\naddress=/ads.example.com/0.0.0.0'
    expect(parseDnsmasq(input)).toEqual(['ads.example.com'])
  })

  it('boş satırları atlar', () => {
    const input = '\naddress=/ads.example.com/0.0.0.0\n\n'
    expect(parseDnsmasq(input)).toEqual(['ads.example.com'])
  })

  it('tekrarlayan domainleri tekilleştirir', () => {
    const input = 'address=/ads.example.com/0.0.0.0\naddress=/ads.example.com/127.0.0.1'
    expect(parseDnsmasq(input)).toEqual(['ads.example.com'])
  })

  it('büyük harfli domain küçük harfe çevirir', () => {
    expect(parseDnsmasq('address=/ADS.EXAMPLE.COM/0.0.0.0')).toContain('ads.example.com')
  })

  it('boş içerik için boş dizi döndürür', () => {
    expect(parseDnsmasq('')).toEqual([])
  })

  // ── Gerçek dünya listesi ──────────────────────────────────────
  it('gerçekçi dnsmasq listesini doğru işler (address + server + local)', () => {
    const input = [
      '# dnsmasq configuration — generated by Hagezi',
      'address=/ads.example.com/0.0.0.0',
      'address=/tracker.io/127.0.0.1',
      'server=/malware.bad.com/#',
      'address=/doubleclick.net/0.0.0.0',
      'local=/cdn.hagezi.com/0.0.0.0',
    ].join('\n')
    const result = parseDnsmasq(input)
    expect(result).toHaveLength(5)
    expect(result).toContain('ads.example.com')
    expect(result).toContain('tracker.io')
    expect(result).toContain('malware.bad.com')
    expect(result).toContain('doubleclick.net')
    expect(result).toContain('cdn.hagezi.com')
  })

  // ── Bulldozer (garbage tolerance) testleri ───────────────────
  it('çöp metin ve bozuk satırlarla dolu içerikten geçerli domainleri çıkarır', () => {
    const input = [
      '<!DOCTYPE html>',
      '<html><head><title>403 Forbidden</title></head>',
      '<body><h1>Access Denied</h1><p>Sorry, you cannot access this file.</p></body>',
      '</html>',
      '===========================================',
      'YANLIIIIŞ FORMAT!!!',
      'random garbage @#$%^&*()',
      '',
      '# Actual dnsmasq data below',
      'address=/ads.example.com/0.0.0.0',
      'NOT VALID LINE AT ALL',
      'address=/tracker.io/127.0.0.1',
      '   totally wrong   ',
      'local=/cdn.block.net/0.0.0.0',
    ].join('\n')
    const result = parseDnsmasq(input)
    expect(result).toHaveLength(3)
    expect(result).toContain('ads.example.com')
    expect(result).toContain('tracker.io')
    expect(result).toContain('cdn.block.net')
  })

  it('uzun preamble (readme/lisans metni) içeren dosyayı işler', () => {
    const preamble = Array(50).fill(0).map((_, i) =>
      `# Line ${i + 1}: Bu bir lisans/açıklama satırıdır. Lütfen dikkatlice okuyunuz.`
    ).join('\n')
    const data = [
      'address=/ads.example.com/0.0.0.0',
      'address=/malware.bad.com/0.0.0.0',
    ].join('\n')
    const result = parseDnsmasq(preamble + '\n' + data)
    expect(result).toHaveLength(2)
    expect(result).toContain('ads.example.com')
    expect(result).toContain('malware.bad.com')
  })
})
